version: '3.8'

services:
  inventario:
    build: .
    container_name: inventario_iso27001
    ports:
      - "5000:5000"
    volumes:
      - inventario_data:/app
    restart: always

volumes:
  inventario_data:
